SELECT
  P.CODAUXILIAR AS "EAN",
  P.CODPROD AS "CÓDIGO",
  P.DESCRICAO AS "DESCRIÇÃO",
  M.MARCA,
  P.CODFAB AS "COD FORNEC.",
  P.QTUNITCX AS "CX PAD.",
  COALESCE((COALESCE(E.QTESTGER,0)+COALESCE(E.AD_MASCARA,0)),0) AS "FÍSICO",
  COALESCE((COALESCE(E.QTRESERV,0) + COALESCE(E.QTPENDENTE,0)),0) AS RESERVADO,
  COALESCE((COALESCE(E.QTESTGER,0) - (COALESCE(E.QTRESERV,0) + COALESCE(E.QTBLOQUEADA,0))) + COALESCE(E.AD_MASCARA,0),0) AS "DISPONÍVEL",
  COALESCE(E.QTPEDIDA, 0) AS "PENDÊNCIA",
  COALESCE(E.QTVENDMES,0) AS MES01,
  COALESCE(E.QTVENDMES1,0) AS MES02,
  COALESCE(E.QTVENDMES2,0) AS MES03,
  ((COALESCE(E.QTVENDMES3,0))-(COALESCE(E.AD_MASCARA,0))) AS MES04,
  COALESCE(ROUND((E.QTVENDMES1 + E.QTVENDMES2 + E.QTVENDMES3) / NULLIF(3, 0), 0),0) AS "MÉDIA",
  COALESCE(ROUND(((E.QTESTGER - COALESCE(E.QTRESERV,0)) / NULLIF((E.QTVENDMES + E.QTVENDMES1 + E.QTVENDMES2) / NULLIF(3, 0), 0)) * 30, 0),0) AS "DIAS DE ESTOQUE"
FROM PCPRODUT P
JOIN PCEST E ON E.CODPROD = P.CODPROD
JOIN PCFORNEC F ON F.CODFORNEC = P.CODFORNEC
JOIN PCMARCA M ON M.CODMARCA = P.CODMARCA
  WHERE E.CODFILIAL = 1
   AND M.CODMARCA = :CODMARCA
   AND M.CODMARCA NOT IN(1821,1916)
   AND P.OBS2 <> 'FL'
ORDER BY P.DESCRICAO